print("Welcome to the Interactive Personal Data Collector!")
print(" ")
name=input("Please Enter your Name: ")
age=int(input("Please Enter your Age: "))
height=float(input("Please Enter your Height in meters: "))
fav_number=int(input("Pleasse Enter your Favourite number: "))
print(" ")
print("Thank you! Here is the information we collected:")
print(" ")
print("Name:", name, "( Type:",type(name), ", Memory Address:",id(name),")")
print("Age:", age, "( Type:",type(age), ", Memory Address:",id(age),")")
print("Height:", height, "( Type:",type(height), ", Memory Address:",id(height),")")
print("Favourite Number:", fav_number, "( Type:",type(fav_number), ", Memory Address:",id(fav_number),")")
print(" ")
print("Your Birth year is approximately: ", 2025-age ,"( based on your Age of", age, ")")
print(" ")
print("Thank you for using the Personal Data Collector. Goodbye!")