print("Welcome to the Interactive Personal Data Collector!")
print(" ")
a=input("Please Enter your Name: ")
b=int(input("Please Enter your Age: "))
c=float(input("Please Enter your Height in meters: "))
d=int(input("Pleasse Enter your Favourite number: "))
print(" ")
print("Thank you! Here is the information we collected:")
print(" ")
print("Name:", a, "( Type:",type(a), "Memory Address:",id(a),")")
print("Age:", b, "( Type:",type(a), "Memory Address:",id(a),")")
print("Height:", c, "( Type:",type(a), "Memory Address:",id(a),")")
print("Favourite Number:", d, "( Type:",type(a), "Memory Address:",id(a),")")
print(" ")
print("Your Birth year is approximately: ", 2025-b ,"( based on your Age of", b, ")")
print(" ")
print("Thank you for using the Personal Data Collector. Goodbye!")